name: trigger gitlab job
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        host: ${{ secrets.GIT_LAB_HOST }}
        token: ${{ secrets.GIT_LAB_TOKEN }}
        project_id: 4757
        ref: "main"
